routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('posts', 'PostController');
Route::resource('comments', 'CommentController');



Route::get('category-tree-view',['uses'=>'CategoryController@manageCategory']);

Route::post('add-category',['as'=>'add.category','uses'=>'CategoryController@addCategory']);

app/Category.php
<?php


namespace App;


use Illuminate\Database\Eloquent\Model;


class Category extends Model

{


    public $fillable = ['title','parent_id'];


    /**

     * Get the index name for the model.

     *

     * @return string

     */

    public function childs() {

        return $this->hasMany(Category::class,'parent_id','id') ;

    }

}

app/Comment.php
<?php



namespace App;



use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;



class Comment extends Model

{

    use SoftDeletes;



    protected $dates = ['deleted_at'];



    /**

     * The attributes that are mass assignable.

     *

     * @var array

     */

    protected $fillable = ['user_id', 'post_id', 'parent_id', 'body'];



    /**

     * The belongs to Relationship

     *

     * @var array

     */

    public function user()

    {

        return $this->belongsTo(User::class);

    }



    /**

     * The has Many Relationship

     *

     * @var array

     */

    public function replies()

    {

        return $this->hasMany(Comment::class, 'parent_id');

    }

}

app/Post.php
<?php



namespace App;



use Illuminate\Database\Eloquent\Model;

use Illuminate\Database\Eloquent\SoftDeletes;



class Post extends Model

{

    use SoftDeletes;



    protected $dates = ['deleted_at'];



    /**

     * The attributes that are mass assignable.

     *

     * @var array

     */

    protected $fillable = ['title', 'body'];



    /**

     * The has Many Relationship

     *

     * @var array

     */

    public function comments()

    {

        return $this->hasMany(Comment::class)->whereNull('parent_id');

    }

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CategoryController.php
<?php


namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\Category;


class CategoryController extends Controller

{

    /**

     * Show the application dashboard.

     *

     * @return \Illuminate\Http\Response

     */

    public function manageCategory()

    {

        $categories = Category::where('parent_id', '=', 0)->get();

        $allCategories = Category::pluck('title','id')->all();

        return view('category.categoryTreeview',compact('categories','allCategories'));

    }


    /**

     * Show the application dashboard.

     *

     * @return \Illuminate\Http\Response

     */

    public function addCategory(Request $request)

    {

        $this->validate($request, [

            'title' => 'required',

        ]);

        $input = $request->all();

        $input['parent_id'] = empty($input['parent_id']) ? 0 : $input['parent_id'];



        Category::create($input);

        return back()->with('success', 'New Category added successfully.');

    }


}

app/Http/Controllers/CommentController.php
<?php



namespace App\Http\Controllers;



use Illuminate\Http\Request;

use App\Comment;



class CommentController extends Controller

{

    /**

     * Store a newly created resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @return \Illuminate\Http\Response

     */

    public function store(Request $request)

    {

        $request->validate([

            'body'=>'required',

        ]);



        $input = $request->all();

        $input['user_id'] = auth()->user()->id;



        Comment::create($input);



        return back();

    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php



namespace App\Http\Controllers;



use Illuminate\Http\Request;

use App\Post;



class PostController extends Controller

{

    /**

     * Display a listing of the resource.

     *

     * @return \Illuminate\Http\Response

     */

    public function index()

    {

        $posts = Post::all();



        return view('posts.index', compact('posts'));

    }



    /**

     * Show the form for creating a new resource.

     *

     * @return \Illuminate\Http\Response

     */

    public function create()

    {

        return view('posts.create');

    }



    /**

     * Store a newly created resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @return \Illuminate\Http\Response

     */

    public function store(Request $request)

    {

        $request->validate([

            'title'=>'required',

            'body'=>'required',

        ]);



        Post::create($request->all());



        return redirect()->route('posts.index');

    }



    /**

     * Show the form for creating a new resource.

     *

     * @return \Illuminate\Http\Response

     */

    public function show($id)

    {

        $post = Post::find($id);

        return view('posts.show', compact('post'));

    }

}

resources/views/category/categoryTreeview.blade.php
<!DOCTYPE html>

<html>

<head>

    <title>Laravel Category Treeview Example</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" />

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <link href="/css/treeview.css" rel="stylesheet">

</head>

<body>

<div class="container">

    <div class="panel panel-primary">

        <div class="panel-heading">Manage Category TreeView</div>

        <div class="panel-body">

            <div class="row">

                <div class="col-md-6">

                    <h3>Category List</h3>

                    <ul id="tree1">

                        @foreach($categories as $category)

                            <li>

                                {{ $category->title }}

                                @if(count($category->childs))

                                    @include('category.manageChild',['childs' => $category->childs])

                                @endif

                            </li>

                        @endforeach

                    </ul>

                </div>

                <div class="col-md-6">

                    <h3>Add New Category</h3>


                    {!! Form::open(['route'=>'add.category']) !!}


                    @if ($message = Session::get('success'))

                        <div class="alert alert-success alert-block">

                            <button type="button" class="close" data-dismiss="alert">×</button>

                            <strong>{{ $message }}</strong>

                        </div>

                    @endif


                    <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">

                        {!! Form::label('Title:') !!}

                        {!! Form::text('title', old('title'), ['class'=>'form-control', 'placeholder'=>'Enter Title']) !!}

                        <span class="text-danger">{{ $errors->first('title') }}</span>

                    </div>


                    <div class="form-group {{ $errors->has('parent_id') ? 'has-error' : '' }}">

                        {!! Form::label('Category:') !!}

                        {!! Form::select('parent_id',$allCategories, old('parent_id'), ['class'=>'form-control', 'placeholder'=>'Select Category']) !!}

                        <span class="text-danger">{{ $errors->first('parent_id') }}</span>

                    </div>


                    <div class="form-group">

                        <button class="btn btn-success">Add New</button>

                    </div>


                    {!! Form::close() !!}


                </div>

            </div>




        </div>

    </div>

</div>

<script src="/js/treeview.js"></script>

</body>

</html>

resources/views/category/manageChild.blade.php
<ul>

    @foreach($childs as $child)

        <li>

            {{ $child->title }}

            @if(count($child->childs))

                @include('category.manageChild',['childs' => $child->childs])

            @endif

        </li>

    @endforeach

</ul>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/posts/commentsDisplay.blade.php
@foreach($comments as $comment)

    <div class="display-comment" @if($comment->parent_id != null) style="margin-left:40px;" @endif>

        <strong>{{ $comment->user->name }}</strong>

        <p>{{ $comment->body }}</p>

        <a href="" id="reply"></a>

        <form method="post" action="{{ route('comments.store') }}">

            @csrf

            <div class="form-group">

                <input type="text" name="body" class="form-control" />

                <input type="hidden" name="post_id" value="{{ $post_id }}" />

                <input type="hidden" name="parent_id" value="{{ $comment->id }}" />

            </div>

            <div class="form-group">

                <input type="submit" class="btn btn-primary" value="Reply" />

            </div>

        </form>

        @include('posts.commentsDisplay', ['comments' => $comment->replies])

    </div>

@endforeach

resources/views/posts/create.blade.php
@extends('layouts.app')



@section('content')

    <div class="container">

        <div class="row justify-content-center">

            <div class="col-md-8">

                <div class="card">

                    <div class="card-header">Create Post</div>

                    <div class="card-body">

                        <form method="post" action="{{ route('posts.store') }}">

                            <div class="form-group">

                                @csrf

                                <label class="label">Post Title: </label>

                                <input type="text" name="title" class="form-control" required/>

                            </div>

                            <div class="form-group">

                                <label class="label">Post Body: </label>

                                <textarea name="body" rows="10" cols="30" class="form-control" required></textarea>

                            </div>

                            <div class="form-group">

                                <input type="submit" class="btn btn-success" />

                            </div>

                        </form>

                    </div>

                </div>

            </div>

        </div>

    </div>

@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')



@section('content')

    <div class="container">

        <div class="row justify-content-center">

            <div class="col-md-12">

                <h1>Manage Posts</h1>

                <a href="{{ route('posts.create') }}" class="btn btn-success" style="float: right">Create Post</a>

                <table class="table table-bordered">

                    <thead>

                    <th width="80px">Id</th>

                    <th>Title</th>

                    <th width="150px">Action</th>

                    </thead>

                    <tbody>

                    @foreach($posts as $post)

                        <tr>

                            <td>{{ $post->id }}</td>

                            <td>{{ $post->title }}</td>

                            <td>

                                <a href="{{ route('posts.show', $post->id) }}" class="btn btn-primary">View Post</a>

                            </td>

                        </tr>

                    @endforeach

                    </tbody>



                </table>

            </div>

        </div>

    </div>

@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')



@section('content')

    <div class="container">

        <div class="row justify-content-center">

            <div class="col-md-8">

                <div class="card">

                    <div class="card-body">

                        <h3 class="text-center text-success">Commenting System</h3>

                        <br/>

                        <h2>{{ $post->title }}</h2>

                        <p>

                            {{ $post->body }}

                        </p>

                        <hr />

                        <h4>Display Comments</h4>



                        @include('posts.commentsDisplay', ['comments' => $post->comments, 'post_id' => $post->id])



                        <hr />

                        <h4>Add comment</h4>

                        <form method="post" action="{{ route('comments.store'   ) }}">

                            @csrf

                            <div class="form-group">

                                <textarea class="form-control" name="body"></textarea>

                                <input type="hidden" name="post_id" value="{{ $post->id }}" />

                            </div>

                            <div class="form-group">

                                <input type="submit" class="btn btn-success" value="Post a Comment" />

                            </div>

                        </form>

                    </div>

                </div>

            </div>

        </div>

    </div>

@endsection